app.locale=es
person.names.min.length=2
person.names.max.length=40
person.lastnames.min.length=2
person.lastnames.max.length=40
person.list.page.size=10
product.price.max=99999999.99
product.description.format=UPPER
