app.locale=es
person.names.min.length=3
person.names.max.length=60
person.lastnames.min.length=3
person.lastnames.max.length=60
person.list.page.size=10
person.collection.mode=QUEUE
product.price.max=99999999.99
product.description.format=UPPER
accounting.collection.mode=STACK
